### ISSUE TITLE
Visitor can remove items from cart

### ISSUE THREAD

**Issue by alfosco** [alfosco/pog_hogs#5]
title: Removing an item from my cart
    body: >
      Background: My cart has an item in it
      As a visitor
      When I visit "/cart"
      And I click link "Remove"
      Then my current page should be "/cart"
      And I should see a message styled in green
      And the message should say "Successfully removed SOME_ITEM from your cart."
      And the title "SOME_ITEM" should be a link to that item in case the user wants to add it back
      And I should not see the item listed in cart

**Comment by maxglassie** [comment]
test written

**Comment by maxglassie** [comment]
For cart items
- build an array of objects to pass to the view, rather than a hash
- build a new PORO - cart_items
- be able to call quantity on cart_items 
- use a module called simple_delegator to create cart_items objects from items objects
- it will pass the attributes from the items so they can be accessed as methods on the PORO
- cart_item can have quantity, calculate it’s own sub-total
